---
  - name: Setting zsh as the default shell...
    command:
      cmd: chsh -s /bin/zsh ominousshell
    become: true

  - name: Configuring zsh...
    copy:
      src: /home/ominousshell/kali-build/roles/setup/configurations/zsh/files/.zshrc
      dest: /home/ominousshell/.zshrc
      owner: ominousshell
      group: ominousshell
      mode: '0644'
    become: true

