---
  - name: Configuring vscodium...
    #User settings
    shell: rm -rf /home/ominousshell/.config/VSCodium/User
  - name:
    unarchive:
      src: /home/ominousshell/kali-build/roles/setup/applications/vscodium/files/vscodim.tar.gz
      dest: /home/ominousshell/.config/VSCodium/User

    #Extensions
  - name:
    shell: rm -rf /home/ominousshell/.vscode-oss/extensions/
  - name:
    unarchive:
      src: /home/ominousshell/kali-build/roles/setup/applications/vscodium/files/extensions.tar.gz
      dest: /home/ominousshell/.vscode-oss/extensions
