---
  - name: Configuring vscodium...
    #User settings
    shell: rm -rf /home/ominousshell/.config/VSCodium/User/
  - name: 
    unarchive:
      src: /home/ominousshell/kali-build/roles/setup/applications/vscodium/files/vscodium.tar.gz
      dest: /home/ominousshell/.config/VSCodium/

    #Extensions
  - name: Configuring vscodium extensions...
    shell: cat /home/ominousshell/kali-build/roles/setup/applications/vscodium/files/extension.txt | xargs -L 1 codium --no-sandbox --user-data-dir /home/ominousshell/ --install-extension
