---
  - include_vars: /home/ominousshell/kali-build/static_variables.yml
  - name: Backing up Tmux configuration...
    copy:
      src: /etc/tmux.conf
      dest: "{{ BASE_DIR }}roles/configurations/tmux/files/"
