alias bookstack-up="~/ominousSHELL/scripts/bookstack/bookstack-up.sh"
alias bookstack-down="~/ominousSHELL/scripts/bookstack/bookstack-down.sh"
alias bookstack-restart="~/ominousSHELL/scripts/bookstack/bookstack-restart.sh"
alias bookstack-backup="~/ominousSHELL/scripts/bookstack/bookstack-backup.sh"
alias bookstack-restore="~/ominousSHELL/scripts/bookstack/bookstack-restore.sh"
alias ominousshell-backup="~/ominousSHELL/scripts/ominousshell-backup.sh"
alias ominous-gen="~/ominousSHELL/ominous-gen/main.py"
alias kali-backup="sudo -E ansible-playbook /home/ominousshell/kali-build/backup.yml"
