alias ominousshell-up="~/ominousSHELL/scripts/bookstack/ominousshell-up.sh"
alias ominousshell-down="~/ominousSHELL/scripts/bookstack/ominousshell-down.sh"
alias ominousshell-restart="~/ominousSHELL/scripts/bookstack/ominousshell-restart.sh"
alias ominousshell-bookstack-backup="~/ominousSHELL/scripts/bookstack/bookstack-backup.sh"
alias ominousshell-bookstack-restore="~/ominousSHELL/scripts/bookstack/bookstack-restore.sh"
alias ominousshell-backup="~/ominousSHELL/scripts/ominousshell-backup.sh"
alias ominous-gen="~/ominousSHELL/ominous-gen/main.py"
alias kali-backup="sudo -E ansible-playbook /home/ominousshell/kali-build/backup.yml"
