---
  - name: Backing up 'kali-build' to USB...
    shell: rm -rf "/home/ominousshell/es/Kali Linux/kali-build/"
  - name:
    copy:
      src: /home/ominousshell/kali-build/ 
      dest: "/home/ominousshell/es/Kali Linux/kali-build/"

  - name: Backing up 'kali-build' to GitHub...
    git_config:
      name: user.email
      value: "ominousshell@proton.me"
      scope: global
  - name: 
    shell: "git add . && git commit -m '1.0' && git push"
    args:
      chdir: /home/ominousshell/kali-build/
