---
  - include_vars: /home/ominousshell/kali-build/static_variables.yml
  - name: Installing Zsh...
    apt:
      name: zsh
      state: latest
  - name: Setting Zsh as default shell...
    shell: echo "{{ PASSWD }}" | su ominousshell -c 'chsh -s /bin/zsh'
  - name: Copying Zsh configuration file...
    copy:
        src: "{{ BASE_DIR }}/roles/configurations/zsh/files/.zshrc"
        dest: /home/ominousshell/.zshrc
    become: true


