---
  - name: Backing up KDE Plasma configuration...
    shell: |
      rm -rf /home/ominousshell/kali-build/roles/configurations/kde-desktop/files/kde-desktop.knsv
      konsave -r kde-desktop
      konsave -s kde-desktop
      konsave -e kde-desktop -d /home/ominousshell/kali-build/roles/configurations/kde-desktop/files/
      sudo chown -R ominousshell:ominousshell /home/ominousshell/.config/

      
#Backup command      
#shell: tar --exclude='*mozilla*' --exclude='*cherrytree*' --exclude='*powershell*' --exclude='*dconf*' --exclude='*app*' -C /home/ominousshell/.config/ -cvJf "{{ BASE_DIR }}/roles/configurations/kde-desktop/files/kde-configurations.tar.xz" .
