---
  - name: Install konsave from pip...
    pip:
      name: konsave
      state: present
    become: true

  - name: Configuring KDE Plasma... 
    shell: |
        konsave -r kde-desktop
        konsave -i /home/ominousshell/kali-build/roles/configurations/kde-desktop/files/kde-desktop.knsv
        konsave -a kde-desktop
    become: true
    become_user: ominousshell

